
// LOGIN/REGISTER/AUTH ACTION TYPES
export const LOGIN_FORM_CHANGE = 'LOGIN_FORM_CHANGE';
export const LOGIN_FORM_CLEANUP = 'LOGIN_FORM_CLEANUP';
export const LOGIN_FORM_SUBMIT = 'LOGIN_FORM_SUBMIT';
export const POST_LOGIN = 'POST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const REGISTER_FORM_CHANGE = 'REGISTER_FORM_CHANGE';
export const REGISTER_FORM_CLEANUP = 'REGISTER_FORM_CLEANUP';
export const REGISTER_FORM_SUBMIT = 'REGISTER_FORM_SUBMIT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// WIZARD ACTION TYPES
export const WIZARD_FORM_CHANGE = 'WIZARD_FORM_CHANGE';
export const WIZARD_PAGE_CHANGE = 'WIZARD_PAGE_CHANGE';
export const WIZARD_CLEANUP = 'WIZARD_CLEANUP';
export const WIZARD_SUBMIT = 'WIZARD_SUBMIT';
export const WIZARD_SUCCESS = 'WIZARD_SUCCESS';
export const WIZARD_FAILURE = 'WIZARD_FAILURE';

// WEDDING DETAILS ACTION TYPES
export const WEDDING_DATE = 'WEDDING_DATE';