
// LOGIN/REGISTER/AUTH ACTION TYPES
export const LOGIN_FORM_CHANGE = 'LOGIN_FORM_CHANGE';
export const LOGIN_FORM_CLEANUP = 'LOGIN_FORM_CLEANUP';
export const LOGIN_FORM_SUBMIT = 'LOGIN_FORM_SUBMIT';
export const POST_LOGIN = 'POST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const REGISTER_FORM_CHANGE = 'REGISTER_FORM_CHANGE';
export const REGISTER_FORM_CLEANUP = 'REGISTER_FORM_CLEANUP';
export const REGISTER_FORM_SUBMIT = 'REGISTER_FORM_SUBMIT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// WIZARD ACTION TYPES
export const WIZARD_FORM_CHANGE = 'WIZARD_FORM_CHANGE';
export const WIZARD_PAGE_CHANGE = 'WIZARD_PAGE_CHANGE';
export const WIZARD_CLEANUP = 'WIZARD_CLEANUP';
export const WIZARD_SUBMIT = 'WIZARD_SUBMIT';
export const WIZARD_SUCCESS = 'WIZARD_SUCCESS';
export const WIZARD_FAILURE = 'WIZARD_FAILURE';

// TODO ACTION TYPES
export const TODO_FILTER = 'TODO_FILTER';
export const TODO_TOGGLE = 'TODO_TOGGLE';
export const TOGGLE_TODO_MENU = 'TOGGLE_TODO_MENU';
export const TODO_CLEANUP = 'TODO_CLEANUP';
export const TODO_SUBMIT = 'TODO_SUBMIT';
export const TODO_SUCCESS = 'TODO_SUCCESS';
export const TODO_FAILURE = 'TODO_FAILURE';
export const TODO_CHANGE = 'TODO_CHANGE';
export const ADD_TODO = 'ADD_TODO';
export const GET_TODO_LIST = 'GET_TODO_LIST';
export const TODO_LIST_SUCCESS = 'TODO_LIST_SUCCESS';
export const TOGGLE_EDIT = 'TOGGLE_EDIT';
export const EDIT_TODO_NAME = 'EDIT_TODO_NAME';
export const POST_TODO_CHANGE = 'POST_TODO_CHANGE';
export const DELETE_TODO = 'DELETE_TODO';

// WEDDING DETAILS ACTION TYPES
export const SET_WEDDING_DETAILS = 'SET_WEDDING_DETAILS';
export const BACK_TO_MENU = 'BACK_TO_MENU';

// VIEW TOGGLE ACTION TYPES
export const VIEW_TOGGLE = 'VIEW_TOGGLE';

//SELECT CARD ACTION TYPES
export const SELECT_CARD = 'SELECT_CARD';

//GUEST FORM ACTION TYPES
export const GUEST_FORM_CHANGE = 'GUEST_FORM_CHANGE';
export const GUEST_FORM_CLEANUP = 'GUEST_FORM_CLEANUP';
export const GUEST_FORM_SUBMIT = 'GUEST_FORM_SUBMIT';
export const POST_GUEST = 'POST_GUEST';

// WEDDING PRESENTATION ACTION TYPES
export const GET_WEDDING_VIEW = 'GET_WEDDING_VIEW';
export const WEDDING_CLEANUP = 'WEDDING_CLEANUP';

