



// LOGIN ACTION TYPES
export const LOGIN_FORM_CHANGE = 'LOGIN_FORM_CHANGE';
export const LOGIN_FORM_CLEANUP = 'LOGIN_FORM_CLEANUP';
export const LOGIN_FORM_SUBMIT = 'LOGIN_FORM_SUBMIT';
export const POST_LOGIN = 'POST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';